### ISSUE TITLE
Getting date error on Mojave

### ISSUE THREAD

**Issue by STiXzoOR** [black-dragon74/OSX-Debug#5]
I'm trying to run the script but i get an error when verifying the EFI files. Heres is the error i get:

```
Verifying your EFI files...


Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.


Failed conversion of ``'' using format ``%Y-%d-%m''
date: illegal time format
usage: date [-jnRu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ...
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
/usr/bin/gen_debug: line 310: 1537463161 - : syntax error: operand expected (error token is " ")
Unmounted /Volumes/EFI
```

how can it be fixed? thanks.

**Comment by black-dragon74** [comment]
Thanks for the report. **This happened due to missing GetFileInfo utility on non-developer environment.** I never worked in non-dev environment and hence never knew this was an issue. Getting script to run on non-dev env will require install of "Command Line Dev Tools" which is around 1.5 GB (not a small download). Many users may have had to download that in order to use gen_debug, sorry for that.

The good news is **with gen_debug version 4.3.1** I have re-written the file age checking protocol and hence **this issue no longer exists** (update rolling out as I type this message). You will get the update prompt automatically else force update by executing **gen_debug -u --force**.

Regards

**Comment by STiXzoOR** [comment]
cool thanks man
